### PR TITLE
Heston volatility should be placed as a parameter of Heston class

### PR DESCRIPTION
**Pull request by masanorihirano**
Currently, Heston class has variance but doesn't have volatility as a buffer.
However, in terms of calculating delta or others, volatility should be registered.

### CODE REVIEW

**Comment by simaki** [comment]
Thank you for the suggestion! It is nice to make volatility accessible as an attribute.

It seems better to make it property from the viewpoint of memory efficiency. What do you think?

**Comment by masanorihirano** [comment]
I apologize I don't know much about memory efficiency.
Thus, I'll leave it to you.

**Comment by masanorihirano** [comment]
Although totally different from this, I think the default value of sigma in Heston class, Heston prossess generation, cir process generation.

Why did you set the sigma to 2.0?

```
from pfhedge.stochastic.cir import generate_cir
generate_cir(10,100, sigma=2.0)
generate_cir(10,100, sigma=0.2)
```

sigma=2.0 seems too big and makes many 0 as a result.
This means no volatility.
I think sigma=0.2 seems better.

https://doi.org/10.1007/978-3-319-05221-2_3
p.75 Fig. 3.1 seems a good reference for it.

**Comment by simaki** [comment]
>Why did you set the sigma to 2.0?

I chose the default parameters as that in the experimental setup of [Deep Hedging](https://arxiv.org/abs/1802.03042) (eq. (5.2)). But I am also skeptical that it is a sensible value because it actually breaks the Feller condition and results in vanishing variances. I appreciate it if you could create a separate issue on that so we can make a further discussion.

**Comment by simaki** [comment]
I think I didn't make it clear enough.
We might want to avoid registering equivalent buffers because a buffer, which typically is of size (10000, 20), can be MB-sized.

Could you take a look at https://github.com/masanorihirano/pfhedge/pull/1 and merge it if looks fine?

**Comment by masanorihirano** [comment]
I have understood basically.
Now, I reviewed your excellent code and accepted the modification.

**Pull request merged**
